# Generated by Django 4.1.6 on 2023-02-19 13:27

from django.db import migrations, models
import django.db.models.deletion
import faculties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('detail', models.TextField()),
                ('detail_html', models.TextField(editable=False)),
                ('faculty_slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VarsityImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='univerrsity/gallery')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=faculties.models.get_image_filename, verbose_name='faculty_image')),
                ('faculty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_images', to='faculties.faculty')),
            ],
        ),
    ]
