# Generated by Django 4.1.6 on 2023-02-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='dean',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
    ]
