# Generated by Django 4.1.6 on 2023-02-19 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='teachers/profile_pics')),
                ('Teacher_ID', models.CharField(max_length=20, unique=True)),
                ('portfolio_site', models.URLField(blank=True)),
                ('academic_rank', models.CharField(choices=[('Lecturer', 'Lecturer'), ('Assistant professor', 'Assistant professor'), ('Associate professor', 'Associate professor'), ('Professor', 'Professor'), ('Professor emeritus', 'Professor emeritus')], max_length=100)),
                ('teacher_slug', models.SlugField(allow_unicode=True, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='departments.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Teacher_ID'],
                'unique_together': {('Teacher_ID', 'department')},
            },
        ),
    ]
